"""
The MIT License (MIT)

Copyright (c) 2026 Error44s

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""

from __future__ import annotations

from typing import Any, Optional

from .helpers import build_current_play_summary


def _fmt_pp(value: float | None) -> str:
    return '-' if value is None else f'{value:.2f}pp'


def _fmt_acc(value: float) -> str:
    return f'{value:.2f}%'


def _fmt_int(value: int | None) -> str:
    return '-' if value is None else f'{value:,}'


def format_analysis_markdown(analysis, beatmap, api_score: dict[str, Any], *, show_timestamps: bool = True) -> str:
    s = build_current_play_summary(analysis, beatmap, api_score)
    status = 'PASSED' if s['passed'] else 'FAILED'
    version = f" [{s['version']}]" if s['version'] else ''
    lines = [
        f"**{s['player']}** — {status}",
        f"{s['artist']} - {s['title']}{version} +{s['mods']}",
        f"Rank: **{s['rank']}** | Score: **{_fmt_int(s['score'])}**",
        f"Acc: **{_fmt_acc(s['accuracy'])}** | Combo: **{s['combo']}x**",
        f"Current: **{_fmt_pp(s['current_pp'])}** | If FC: **{_fmt_pp(s['if_fc_pp'])}** | Choke: **{_fmt_pp(s['choke_pp'])}**",
        f"Progress: **{s['completion_text']}**",
    ]
    if show_timestamps and s.get('created_at'):
        lines.append(f"Played at: **{s['created_at']}**")
    return '\n'.join(lines)


def build_embed_payload(analysis, beatmap, api_score: dict[str, Any], *, color: Optional[int] = None) -> dict[str, Any]:
    s = build_current_play_summary(analysis, beatmap, api_score)
    version = f" [{s['version']}]" if s['version'] else ''
    status = 'Passed' if s['passed'] else 'Failed'
    fields = [
        {'name': 'Accuracy', 'value': _fmt_acc(s['accuracy']), 'inline': True},
        {'name': 'Combo', 'value': f"{s['combo']}x / {s['full_max_combo']}x", 'inline': True},
        {'name': 'Score', 'value': _fmt_int(s['score']), 'inline': True},
        {'name': 'Current PP', 'value': _fmt_pp(s['current_pp']), 'inline': True},
        {'name': 'If FC PP', 'value': _fmt_pp(s['if_fc_pp']), 'inline': True},
        {'name': 'Choke PP', 'value': _fmt_pp(s['choke_pp']), 'inline': True},
        {'name': 'Progress', 'value': s['completion_text'], 'inline': True},
        {
            'name': 'Hitresults',
            'value': (
                f"300: {s['statistics'].count_300} | 100: {s['statistics'].count_100} | "
                f"50: {s['statistics'].count_50} | Miss: {s['statistics'].count_miss}"
            ),
            'inline': False,
        },
    ]
    if s.get('created_at'):
        fields.append({'name': 'Played At', 'value': str(s['created_at']), 'inline': False})
    payload = {
        'title': f"{s['artist']} - {s['title']}{version}",
        'description': f"{status} by {s['player']} | +{s['mods']} | Rank {s['rank']}",
        'fields': fields,
        'footer': {'text': 'Generated by osukit'},
    }
    if color is not None:
        payload['color'] = color
    return payload
